import { createServerFn } from '@tanstack/react-start'
import { z } from 'zod'
import { supabaseAdmin } from '@/integrations/supabase/client.server'
import { getRequest } from '@tanstack/react-start/server'
import { auth } from '#/lib/auth'

async function checkAuth() {
  const request = getRequest()
  const session = await auth.api.getSession({ headers: request.headers })
  if (!session?.user) throw new Error('Unauthorized')
  return session
}

/** Public — anyone can call a waiter (no auth needed) */
export const callWaiter = createServerFn({ method: 'POST' })
  .inputValidator((d) =>
    z
      .object({
        table_number: z.number().int().min(1),
        device_id: z.string(),
      })
      .parse(d),
  )
  .handler(async ({ data }) => {
    // 1. Fetch dynamic max_tables from restaurant_info
    const { data: info } = await supabaseAdmin
      .from('restaurant_info')
      .select('max_tables')
      .limit(1)
      .maybeSingle()

    const maxTables = info?.max_tables ?? 999
    if (data.table_number > maxTables) {
      throw new Error(`Table number cannot exceed ${maxTables}`)
    }

    // 2. Guard: Check if THIS DEVICE has already called recently
    const { data: existing } = await supabaseAdmin
      .from('waiter_calls')
      .select('created_at')
      .eq('device_id', data.device_id)
      .eq('status', 'pending')
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle()

    if (existing) {
      const callTime = new Date(existing.created_at).getTime()
      const now = Date.now()
      // If a pending call exists from less than 10 minutes ago, prevent another call
      if (now - callTime < 10 * 60 * 1000) {
        throw new Error('A waiter is already on their way to your table.')
      }
    }

    // 3. Insert the new call
    const { error } = await supabaseAdmin.from('waiter_calls').insert({
      table_number: data.table_number,
      device_id: data.device_id,
      status: 'pending',
    })

    if (error) throw new Error(error.message)
    return { ok: true }
  })

/** Admin — get all pending/recent calls */
export const getWaiterCalls = createServerFn({ method: 'GET' }).handler(
  async () => {
    await checkAuth()
    const { data, error } = await supabaseAdmin
      .from('waiter_calls')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(50)
    if (error) throw new Error(error.message)
    return data ?? []
  },
)

/** Admin — acknowledge a call */
export const acknowledgeCall = createServerFn({ method: 'POST' })
  .inputValidator((d) => z.object({ id: z.string().uuid() }).parse(d))
  .handler(async ({ data }) => {
    await checkAuth()
    const { error } = await supabaseAdmin
      .from('waiter_calls')
      .update({ status: 'acknowledged' })
      .eq('id', data.id)
    if (error) throw new Error(error.message)
    return { ok: true }
  })

export type WaiterCall = {
  id: string
  table_number: number
  status: string
  created_at: string
}

// ─── Restaurant Tables ────────────────────────────────────────────────────────

/** Public — verify a table token from QR code */
export const verifyTableToken = createServerFn({ method: 'POST' })
  .inputValidator((d) => z.object({ token: z.string().min(1) }).parse(d))
  .handler(async ({ data }) => {
    const { data: table, error } = await supabaseAdmin
      .from('restaurant_tables')
      .select('id, label, is_active')
      .eq('token', data.token)
      .maybeSingle()

    if (error || !table) throw new Error('Invalid QR code')
    if (!table.is_active) throw new Error('This table is currently inactive')
    return { id: table.id, label: table.label }
  })

/** Admin — list all tables */
export const getTables = createServerFn({ method: 'GET' }).handler(async () => {
  await checkAuth()
  const { data, error } = await supabaseAdmin
    .from('restaurant_tables')
    .select('*')
    .order('created_at', { ascending: true })
  if (error) throw new Error(error.message)
  return data ?? []
})

/** Admin — create or rename a table */
export const upsertTable = createServerFn({ method: 'POST' })
  .inputValidator((d) =>
    z
      .object({ id: z.string().uuid().optional(), label: z.string().min(1) })
      .parse(d),
  )
  .handler(async ({ data }) => {
    await checkAuth()
    if (data.id) {
      // Update label only
      const { error } = await supabaseAdmin
        .from('restaurant_tables')
        .update({ label: data.label })
        .eq('id', data.id)
      if (error) throw new Error(error.message)
    } else {
      // Insert new table — token is auto-generated by DB default
      const { error } = await supabaseAdmin
        .from('restaurant_tables')
        .insert({ label: data.label })
      if (error) throw new Error(error.message)
    }
    return { ok: true }
  })

/** Admin — rotate the token for a table (invalidates old QR code) */
export const regenerateTableToken = createServerFn({ method: 'POST' })
  .inputValidator((d) => z.object({ id: z.string().uuid() }).parse(d))
  .handler(async ({ data }) => {
    await checkAuth()
    const newToken = crypto.randomUUID()

    const { error: updateError } = await supabaseAdmin
      .from('restaurant_tables')
      .update({ token: newToken })
      .eq('id', data.id)

    if (updateError) throw new Error(updateError.message)
    return { ok: true, token: newToken }
  })

/** Admin — soft-delete (deactivate) a table */
export const deleteTable = createServerFn({ method: 'POST' })
  .inputValidator((d) => z.object({ id: z.string().uuid() }).parse(d))
  .handler(async ({ data }) => {
    await checkAuth()
    const { error } = await supabaseAdmin
      .from('restaurant_tables')
      .delete()
      .eq('id', data.id)
    if (error) throw new Error(error.message)
    return { ok: true }
  })

// ─── Table Orders ─────────────────────────────────────────────────────────────

const OrderItemSchema = z.object({
  id: z.string(),
  name: z.string(),
  qty: z.number().int().min(1),
  price: z.number(),
})

/** Public — place an order from the menu */
export const placeOrder = createServerFn({ method: 'POST' })
  .inputValidator((d) =>
    z
      .object({
        table_id: z.string().uuid(),
        table_label: z.string(),
        items: z.array(OrderItemSchema).min(1).max(20),
        note: z.string().max(300).optional(),
        device_id: z.string(),
      })
      .parse(d),
  )
  .handler(async ({ data }) => {
    // Rate limit: 1 order per 5 min per device
    const { data: recent } = await supabaseAdmin
      .from('table_orders')
      .select('created_at')
      .eq('device_id', data.device_id)
      .in('status', ['pending', 'accepted'])
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle()

    if (recent) {
      const elapsed = Date.now() - new Date(recent.created_at).getTime()
      if (elapsed < 5 * 60 * 1000) {
        throw new Error(
          'You already have an active order. Please wait for it to be accepted before ordering again.',
        )
      }
    }

    const { error } = await supabaseAdmin.from('table_orders').insert({
      table_id: data.table_id,
      table_label: data.table_label,
      items: data.items,
      note: data.note ?? null,
      device_id: data.device_id,
      status: 'pending',
    })

    if (error) throw new Error(error.message)
    return { ok: true }
  })

/** Admin — get all orders (latest first) */
export const getTableOrders = createServerFn({ method: 'GET' }).handler(
  async () => {
    await checkAuth()
    const { data, error } = await supabaseAdmin
      .from('table_orders')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(100)
    if (error) throw new Error(error.message)
    return data ?? []
  },
)

/** Admin — update order status */
export const updateOrderStatus = createServerFn({ method: 'POST' })
  .inputValidator((d) =>
    z
      .object({
        id: z.string().uuid(),
        status: z.enum(['accepted', 'rejected', 'completed']),
      })
      .parse(d),
  )
  .handler(async ({ data }) => {
    await checkAuth()
    const { error } = await supabaseAdmin
      .from('table_orders')
      .update({ status: data.status })
      .eq('id', data.id)
    if (error) throw new Error(error.message)
    return { ok: true }
  })

export type RestaurantTable = {
  id: string
  label: string
  token: string
  is_active: boolean
  created_at: string
}

export type TableOrder = {
  id: string
  table_id: string
  table_label: string
  items: Array<{ id: string; name: string; qty: number; price: number }>
  note: string | null
  status: 'pending' | 'accepted' | 'rejected' | 'completed'
  device_id: string
  created_at: string
}
