/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiSeedAdminRouteImport } from './routes/api/seed-admin'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedAdminRoute = ApiSeedAdminRouteImport.update({
  id: '/api/seed-admin',
  path: '/api/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/staff': typeof StaffRoute
  '/staff-login': typeof StaffLoginRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/seed-admin': typeof ApiSeedAdminRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/staff': typeof StaffRoute
  '/staff-login': typeof StaffLoginRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/seed-admin': typeof ApiSeedAdminRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/staff': typeof StaffRoute
  '/staff-login': typeof StaffLoginRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/seed-admin': typeof ApiSeedAdminRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/staff'
    | '/staff-login'
    | '/api/ai-chat'
    | '/api/seed-admin'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/staff'
    | '/staff-login'
    | '/api/ai-chat'
    | '/api/seed-admin'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/privacy'
    | '/staff'
    | '/staff-login'
    | '/api/ai-chat'
    | '/api/seed-admin'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  StaffRoute: typeof StaffRoute
  StaffLoginRoute: typeof StaffLoginRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiSeedAdminRoute: typeof ApiSeedAdminRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-admin': {
      id: '/api/seed-admin'
      path: '/api/seed-admin'
      fullPath: '/api/seed-admin'
      preLoaderRoute: typeof ApiSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  StaffRoute: StaffRoute,
  StaffLoginRoute: StaffLoginRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiSeedAdminRoute: ApiSeedAdminRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
